=== xShadowArmy/digital-commissioning-tool/DigitalCommissioningTool/Output/Resources/ProjectContainerSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Projects/" 
           targetNamespace="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Projects/"
           elementFormDefault="qualified" attributeFormDefault="qualified">

<!-- definition of Simple Elements -->

  <!-- definition of Attributes -->
  <xs:attribute name="count" type="xs:unsignedLong"/>
  <xs:attribute name="id" type="xs:unsignedLong"/>
  <xs:attribute name="idRef" type="xs:unsignedLong"/>
  <xs:attribute name="x" type="xs:double"/>
  <xs:attribute name="y" type="xs:double"/>
  <xs:attribute name="z" type="xs:double"/>

  <!-- definition of Complex elements -->
  <xs:element name="Position">
    <xs:complexType>
      <xs:attribute ref="x" use="required"/>
      <xs:attribute ref="y" use="required"/>
      <xs:attribute ref="z" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Rotation">
    <xs:complexType>
      <xs:attribute ref="x" use="required"/>
      <xs:attribute ref="y" use="required"/>
      <xs:attribute ref="z" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Scale">
    <xs:complexType>
      <xs:attribute ref="x" use="required"/>
      <xs:attribute ref="y" use="required"/>
      <xs:attribute ref="z" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Transform">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Position" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="Rotation" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="Scale" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Position" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="Rotation" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="Scale" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="idRef" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Items">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="count" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Storage">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Transform" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="Items" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ProjectContainer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Storage" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== xShadowArmy/digital-commissioning-tool/DigitalCommissioningTool/Output/Projects/Container.xml
<?xml version="1.0" encoding="utf-8"?>
<xs:ProjectContainer xs:count="1" xmlns:xs="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Resources/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Resources/ ProjectContainerSchema.xsd">
    <xs:Container xs:slotCount="20" xs:id="1">
        <xs:Transform>
            <xs:Position xs:x="4.636045" xs:y="0" xs:z="4.91227">
            </xs:Position>
            <xs:Rotation xs:x="0" xs:y="2.075432E-19" xs:z="0">
            </xs:Rotation>
            <xs:Scale xs:x="1" xs:y="1" xs:z="1">
            </xs:Scale>
        </xs:Transform>
        <xs:Items xs:count="20">
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
            <xs:Item xs:itemName="null">
            </xs:Item>
        </xs:Items>
    </xs:Container>
</xs:ProjectContainer>
