=== xShadowArmy/digital-commissioning-tool/Software/Quellen/DigitalCommissioningTool/Output/Resources/ConfigSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Resources" 
           targetNamespace="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Resources"
           elementFormDefault="qualified" attributeFormDefault="qualified">

<!-- definition of Simple Elements -->
  <xs:element name="Value" type="xs:string"/>
  
<!-- definition of Attributes -->
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="id" type="xs:long"/>
  <xs:attribute name="type" type="xs:string"/>
  <xs:attribute name="value" type="xs:string"/>
  <xs:attribute name="isArray" type="xs:boolean"/>
  <xs:attribute name="elementCount" type="xs:unsignedLong"/>
  <xs:attribute name="propertyCount" type="xs:unsignedLong"/>
  <xs:attribute name="dataCount" type="xs:long"/>
    
<!-- definition of Complex elements -->
  <xs:element name="Values">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Property" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="propertyCount" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Property">
    <xs:complexType>
      <xs:attribute ref="type" use="required"/>
      <xs:attribute ref="value" use="required"/>
    </xs:complexType>
  </xs:element> 
  
  <xs:element name="SimpleData">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Value" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute ref="type" use="required"/>
      <xs:attribute ref="isArray" use="required"/>
      <xs:attribute ref="elementCount" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ComplexData">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Values" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="type" use="required"/>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute ref="isArray" use="required" fixed="false"/>
      <xs:attribute ref="elementCount" use="required" fixed="1"/>
    </xs:complexType>
  </xs:element>

  <xs:group name="Data">
    <xs:choice>
      <xs:element ref="SimpleData"/>
      <xs:element ref="ComplexData"/>
    </xs:choice>
  </xs:group>

  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="Data" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="dataCount" use="required"/>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== xShadowArmy/digital-commissioning-tool/Software/Produkt/DigitalCommisioningTool/Resources/Data/Paths.xml
<?xml version="1.0" encoding="utf-8"?>
<xs:Config xs:dataCount="2" xmlns:xs="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Resources/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Resources/ ConfigSchema.xsd">
    <xs:SimpleData xs:name="vals" xs:id="1" xs:type="String" xs:isArray="true" xs:elementCount="12">
        <xs:Value>.\Output\Logs\</xs:Value>
        <xs:Value>.\Logs\</xs:Value>
        <xs:Value>.\Output\Resources\Strings\</xs:Value>
        <xs:Value>.\Resources\Strings\</xs:Value>
        <xs:Value>.\Output\Resources\Data\</xs:Value>
        <xs:Value>.\Resources\Data\</xs:Value>
        <xs:Value>.\Output\Resources\</xs:Value>
        <xs:Value>.\Resources\</xs:Value>
        <xs:Value>.\Output\Projects\</xs:Value>
        <xs:Value>.\Projects\</xs:Value>
        <xs:Value>.\Output\Temp\</xs:Value>
        <xs:Value>.\Temp\</xs:Value>
    </xs:SimpleData>
    <xs:SimpleData xs:name="keys" xs:id="2" xs:type="String" xs:isArray="true" xs:elementCount="12">
        <xs:Value>LogPathDebug</xs:Value>
        <xs:Value>LogPathRelease</xs:Value>
        <xs:Value>StringResourcePathDebug</xs:Value>
        <xs:Value>StringResourcePathRelease</xs:Value>
        <xs:Value>DataResourcePathDebug</xs:Value>
        <xs:Value>DataResourcePathRelease</xs:Value>
        <xs:Value>ResourcePathDebug</xs:Value>
        <xs:Value>ResourcePathRelease</xs:Value>
        <xs:Value>ProjectsPathDebug</xs:Value>
        <xs:Value>ProjectsPathRelease</xs:Value>
        <xs:Value>TempPathDebug</xs:Value>
        <xs:Value>TempPathRelease</xs:Value>
    </xs:SimpleData>
</xs:Config>
